GET http://localhost:8000/api/tasks/1

###

POST http://localhost:8000/api/tasks/
Content-Type: application/json

{
    "title": "Nauczyć się DRF",
    "description": "Przerobić lekcję i zadania."
}

###

PATCH http://localhost:8000/api/tasks/1/
Content-Type: application/json

{
    "completed": true
}