# Generated by Django 6.0.7 on 2026-07-12 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa dealera')),
                ('address', models.TextField(verbose_name='Adres')),
            ],
            options={
                'verbose_name': 'Dealer',
                'verbose_name_plural': 'Dealerzy',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Marka')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('year', models.IntegerField(verbose_name='Rok produkcji')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('description', models.TextField(verbose_name='Opis')),
                ('photo', models.ImageField(upload_to='cars/', verbose_name='Zdjęcie')),
                ('owner_website', models.URLField(blank=True, null=True, verbose_name='Strona właściciela')),
                ('is_available', models.BooleanField(default=True, verbose_name='Dostępny')),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.dealer', verbose_name='Dealer')),
            ],
            options={
                'verbose_name': 'Samochód',
                'verbose_name_plural': 'Samochody',
            },
        ),
    ]
