class ConnectionError(Exception):
    ...
    
class NoResponseError(ConnectionError):
    ...
    
class EmptyResponseError(ConnectionError):
    ...
    
class DamagedResponseError(ConnectionError):
    ...