[project]
name = "lesson27"
version = "0.1.0"
description = "Collection of Django REST Framework examples including JWT, serializers, middleware, testing and REST API development.""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.7",
    "djangorestframework>=3.17.1",
]