# Generated by Django 6.1 on 2026-08-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_tasks', '0002_scrapedpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_images/')),
                ('classification_result', models.CharField(blank=True, max_length=255)),
                ('image_type', models.CharField(blank=True, max_length=20)),
                ('image_format', models.CharField(blank=True, max_length=20)),
                ('image_mode', models.CharField(blank=True, max_length=20)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('orientation', models.CharField(blank=True, max_length=20)),
                ('pixel_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('has_alpha', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
