# Generated by Django 6.0.8 on 2026-08-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ogloszenie',
            options={'ordering': ['-data_dodania'], 'verbose_name': 'Ogłoszenie', 'verbose_name_plural': 'Ogłoszenia'},
        ),
    ]
