# Generated by Django 6.1 on 2026-08-07 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_dealer_car_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.dealer'),
        ),
    ]
