"""Dodanie daty utworzenia

Revision ID: cd87948e7809
Revises: 1fa3c8e6553c
Create Date: 2026-06-06 01:24:37.634548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd87948e7809'
down_revision: Union[str, Sequence[str], None] = '1fa3c8e6553c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
